name: ArchLinux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

jobs:
  test:
    runs-on: ubuntu-20.04

    container: archlinux

    steps:
      - run: pacman -Syy --noconfirm
      - run: pacman -S   --noconfirm git file


      ## pre-checkout sequence

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'

      ## post-checkout sequence
      - run: make
      - run: make help
      - run: make docker-start
      - run: make report
      - run: make submodules
      - run: make initialize

      ## build example
      #- run:  if [ ! -d ctags ]; then git clone https://github.com/universal-ctags/ctags; fi
      #- run: apt -y install gcc make pkg-config autoconf automake python3-docutils libseccomp-dev libjansson-dev libyaml-dev libxml2-dev
      #- run: install autogen.sh ctags
      #- run: cd ctags && ./autogen.sh configure
      #- run: cd ctags && ./configure --prefix=/usr
      #- run: cd ctags && make
      #- run: cd ctags && make install
      #- run: file /usr/bin/ctags
      #- run: /usr/bin/ctags --version

      ## sequence success!!
      - run: make tag 2>/dev/null

