name: LinuxMint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        tag: [19.3]#, 20.1]

    container: linuxmintd/mint${{ matrix.tag }}-amd64

    steps:
      - run: apt -y update
      - run: apt -y install gcc make pkg-config autoconf automake python3-docutils libseccomp-dev libjansson-dev libyaml-dev libxml2-dev
      - run: apt -y install git file autoconf pkg-config  docker* gettext libtool

      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          submodules: 'true'
          set-safe-directory: 'true'

      - run: make
      - run: make help
      - run: make docker-start
      - run: make report
      - run: make submodules
      - run: make initialize

      - run:  if [ ! -d ctags ]; then git clone https://github.com/universal-ctags/ctags; fi
      - run: install autogen.sh ctags
      - run: cd ctags && ./autogen.sh configure
      - run: cd ctags && ./configure --prefix=/usr
      - run: cd ctags && make
      - run: cd ctags && make install
      - run: file /usr/bin/ctags
      - run: /usr/bin/ctags --version

